#ifndef MAS_DUF_OPT_TYPES_H
#  define MAS_DUF_OPT_TYPES_H

/* #  define DUF_OPTIONS_SHORT "hxRvAeSIQTVfd5EiMuZBPOGgXpmDnY:y" */
typedef enum
{
  DUF_OPTION_NONE,

  DUF_OPTION_HELP = 'h',
  DUF_OPTION_EXAMPLES = 'x',
  DUF_OPTION_TEST = 't',
  DUF_OPTION_VERBOSE = 'v',
  DUF_OPTION_DEBUG = 'g',
  DUF_OPTION_MEMUSAGE = 'M',
/* db general */
  DUF_OPTION_DB_DIRECTORY = 'Y',
  DUF_OPTION_VACUUM = 'V',
  DUF_OPTION_ZERO_DB = 'Z',
  DUF_OPTION_CREATE_TABLES = 'O',
  DUF_OPTION_INTEGRITY = 'G',

  /* trace */
  DUF_OPTION_ACTION_TRACE = 'A',
  DUF_OPTION_SCAN_TRACE = 'S',
  DUF_OPTION_COLLECT_TRACE = 'I',
  DUF_OPTION_SQL_TRACE = 'Q',
  DUF_OPTION_ANY_TRACE = 'y',
  DUF_OPTION_MATCH_TRACE = 'm',
  DUF_OPTION_ALL_TRACE = 'X',
  /* /trace */

  DUF_OPTION_RECURSIVE = 'R',
  DUF_OPTION_TREE_TO_DB = 'B',
  DUF_OPTION_ADD_PATH = 'P',

  /* actions */
  DUF_OPTION_TREE = 'T',
  DUF_OPTION_PRINT = 'p',
  DUF_OPTION_SUMMARY = 'u',

  /* actions */
  DUF_OPTION_COLLECT = 'i',
  DUF_OPTION_FILES = 'f',
  DUF_OPTION_DIRS = 'd',
  DUF_OPTION_DIRENT = 'E',

  DUF_OPTION_FILEDATA = 'D',
  DUF_OPTION_FILENAMES = 'n',
  DUF_OPTION_MD5 = '5',
  DUF_OPTION_MIME = 'e',


/*==================================================*/
  DUF_OPTION_LONG = 1000,
/*==================================================*/

/* db general */
  DUF_OPTION_DB_NAME,
  DUF_OPTION_REMOVE_DATABASE,
  DUF_OPTION_DROP_TABLES,

  /* i/o */
  DUF_OPTION_OUTPUT,
  DUF_OPTION_OUTPUT_FILE,
  DUF_OPTION_FORMAT,

  /* execution control */
  DUF_OPTION_DISABLE_INSERT,
  DUF_OPTION_DISABLE_UPDATE,

  /* trace */
  DUF_OPTION_ERROR_TRACE,
  DUF_OPTION_CURRENT_TRACE,
  DUF_OPTION_SEQ_TRACE,
  DUF_OPTION_CALLS_TRACE,
  DUF_OPTION_DELETED_TRACE,
  DUF_OPTION_DIRENT_TRACE,
  DUF_OPTION_FS_TRACE,
  DUF_OPTION_INTEGRITY_TRACE,
  DUF_OPTION_MD5_TRACE,
  DUF_OPTION_MIME_TRACE,
  DUF_OPTION_MDPATH_TRACE,
  DUF_OPTION_PATH_TRACE,
  DUF_OPTION_SAMPLE_TRACE,
  DUF_OPTION_SAMPUPD_TRACE,

  DUF_OPTION_TRACE_NONEW,

  /* trace i/o */
  DUF_OPTION_TRACE_FILE,
  DUF_OPTION_TRACE_STDERR,
  DUF_OPTION_TRACE_STDOUT,

  /* debug */
  DUF_OPTION_MIN_DBGLINE,
  DUF_OPTION_MAX_DBGLINE,

  DUF_OPTION_NOOPENAT,

  /* actions */
  DUF_OPTION_SAMPLE,
  DUF_OPTION_SAMPUPD,
  DUF_OPTION_MDPATH,
/* /actions */

  /* DUF_OPTION_UPDATE_PATH, */
  /* DUF_OPTION_UPDATE_MD5, */
  /* DUF_OPTION_ZERO_DUPLICATES, */
  /* DUF_OPTION_UPDATE_DUPLICATES, */
  /* DUF_OPTION_UPDATE_MDPATH, */
  /* DUF_OPTION_UPDATE_MDPATH_SELECTIVE, */
  /* DUF_OPTION_UPDATE_FILEDATA, */
  /* DUF_OPTION_ZERO_FILEDATA, */
  /* DUF_OPTION_UPDATE_EXIF, */

  /* filters */
  DUF_OPTION_MINDIRFILES,
  DUF_OPTION_MAXDIRFILES,
  DUF_OPTION_GLOB_INCLUDE_FILES,
  DUF_OPTION_GLOB_EXCLUDE_FILES,
  DUF_OPTION_MD5ID,
  DUF_OPTION_MIMEID,
  DUF_OPTION_SIZE,
  DUF_OPTION_MINSIZE,
  DUF_OPTION_MAXSIZE,
  DUF_OPTION_SAME,
  DUF_OPTION_MINSAME,
  DUF_OPTION_MAXSAME,
  DUF_OPTION_MAXDEPTH,
  DUF_OPTION_MAXSEQ,
  DUF_OPTION_MAXITEMS,
  DUF_OPTION_MAXITEMS_FILES,
  DUF_OPTION_MAXITEMS_DIRS,
  /* /filters */

  DUF_OPTION_UNI_SCAN,

  /* DUF_OPTION_PRINT_PATHS, */
  /* DUF_OPTION_PRINT_DIRS, */
  /* DUF_OPTION_PRINT_FILES, */
  /* DUF_OPTION_PRINT_DUPLICATES, */
  /* DUF_OPTION_SAME_FILES, */
  /* DUF_OPTION_SAME_EXIF, */
  /* DUF_OPTION_SAME_MD5, */
  /* DUF_OPTION_GROUP, */
  /* DUF_OPTION_LIMIT, */
  /* DUF_OPTION_ADD_TO_GROUP, */
  /* DUF_OPTION_REMOVE_FROM_GROUP, */
  DUF_OPTION_MAX_LONG,
} duf_option_code_t;

typedef struct option duf_option_t;


#endif

