#ifndef SQL_BEGINNING_SELECTED_H
#  define SQL_BEGINNING_SELECTED_H

#  define DUF_SQL_SELECTED_TEMPORARY "TEMPORARY"
#  ifdef DUF_SQL_SELECTED_TEMPORARY
#    define DUF_SQL_SELECTED_TEMPORARY_STRING DUF_SQL_SELECTED_TEMPORARY
#  else
#    define DUF_SQL_SELECTED_TEMPORARY_STRING
#  endif

#  define DUF_SQL_SELECTED_NAME  "selected_filenames"
#  define DUF_SQL_SELECTED_PATHS "selected_paths"
#  define DUF_SQL_SELECTED_PATHTOT_FILES "selected_pathtot_files"
#  define DUF_SQL_SELECTED_PATHTOT_DIRS "selected_pathtot_dirs"

#  if 0
#    define DUF_SQL_SELECTED_NAME_FULL  DUF_DBPREF DUF_SQL_SELECTED_NAME
#    define DUF_SQL_SELECTED_PATHS_FULL DUF_DBPREF DUF_SQL_SELECTED_PATHS
#    define DUF_SQL_SELECTED_PATHTOT_FILES_FULL DUF_DBPREF DUF_SQL_SELECTED_PATHTOT_FILES
#    define DUF_SQL_SELECTED_PATHTOT_DIRS_FULL DUF_DBPREF DUF_SQL_SELECTED_PATHTOT_DIRS
#  else
#    define DUF_SQL_SELECTED_NAME_FULL  DUF_SQL_SELECTED_NAME
#    define DUF_SQL_SELECTED_PATHS_FULL DUF_SQL_SELECTED_PATHS
#    define DUF_SQL_SELECTED_PATHTOT_FILES_FULL DUF_SQL_SELECTED_PATHTOT_FILES
#    define DUF_SQL_SELECTED_PATHTOT_DIRS_FULL DUF_SQL_SELECTED_PATHTOT_DIRS
#  endif

#include "sql_beginning_types.h"

extern duf_beginning_t sql_beginning_selected;

#endif
