#ifndef MAS_SQL_SELECTED_DEFS_H
# define MAS_SQL_SELECTED_DEFS_H
# include "duf_defs.h"

# include "sql_tables_global_defs.h"

# define DUF_SQL_SELECTED_TMP_FILENAMES  "${PDI_NAME}_selected_filenames"
# define DUF_SQL_SELECTED_TMP_PATHS "${PDI_NAME}_selected_paths"


# ifdef DUF_SQL_SELECTED_TEMPORARY
#  define DUF_SQL_SELECTED_TMP_FILENAMES_FULL           DUF_SQL_SELECTED_TMP_FILENAMES
#  define DUF_SQL_SELECTED_TMP_PATHS_FULL               DUF_SQL_SELECTED_TMP_PATHS
# else
#  define DUF_SQL_SELECTED_TMP_FILENAMES_FULL     DUF_DBSELECTEDPREF DUF_SQL_SELECTED_TMP_FILENAMES
#  define DUF_SQL_SELECTED_TMP_PATHS_FULL         DUF_DBSELECTEDPREF DUF_SQL_SELECTED_TMP_PATHS
# endif

#endif
