#ifndef SQL_SELECTED_DEFS_H
#  define SQL_SELECTED_DEFS_H

#  define DUF_SQL_SELECTED_TMP_FILENAMES  "t_selected_filenames"
#  define DUF_SQL_SELECTED_TMP_PATHS "t_selected_paths"
#  define DUF_SQL_SELECTED_TMP_PATHTOT_FILES "t_selected_pathtot_files"
#  define DUF_SQL_SELECTED_TMP_PATHTOT_DIRS "t_selected_pathtot_dirs"

#  if 1
#    ifdef DUF_SQL_SELECTED_TEMPORARY
#      define DUF_SQL_SELECTED_TMP_FILENAMES_FULL           DUF_SQL_SELECTED_TMP_FILENAMES
#      define DUF_SQL_SELECTED_TMP_PATHS_FULL               DUF_SQL_SELECTED_TMP_PATHS
#      define DUF_SQL_SELECTED_TMP_PATHTOT_FILES_FULL       DUF_SQL_SELECTED_TMP_PATHTOT_FILES
#      define DUF_SQL_SELECTED_TMP_PATHTOT_DIRS_FULL        DUF_SQL_SELECTED_TMP_PATHTOT_DIRS
#    else
#      if 1
#        define DUF_SQL_SELECTED_TMP_FILENAMES_FULL     DUF_DBSELECTEDPREF DUF_SQL_SELECTED_TMP_FILENAMES
#        define DUF_SQL_SELECTED_TMP_PATHS_FULL         DUF_DBSELECTEDPREF DUF_SQL_SELECTED_TMP_PATHS
#        define DUF_SQL_SELECTED_TMP_PATHTOT_FILES_FULL DUF_DBSELECTEDPREF DUF_SQL_SELECTED_TMP_PATHTOT_FILES
#        define DUF_SQL_SELECTED_TMP_PATHTOT_DIRS_FULL  DUF_DBSELECTEDPREF DUF_SQL_SELECTED_TMP_PATHTOT_DIRS
#      else
#        define DUF_SQL_SELECTED_TMP_FILENAMES_FULL     DUF_DBTOSETPREF DUF_SQL_SELECTED_TMP_FILENAMES
#        define DUF_SQL_SELECTED_TMP_PATHS_FULL         DUF_DBTOSETPREF DUF_SQL_SELECTED_TMP_PATHS
#        define DUF_SQL_SELECTED_TMP_PATHTOT_FILES_FULL DUF_DBTOSETPREF DUF_SQL_SELECTED_TMP_PATHTOT_FILES
#        define DUF_SQL_SELECTED_TMP_PATHTOT_DIRS_FULL  DUF_DBTOSETPREF DUF_SQL_SELECTED_TMP_PATHTOT_DIRS
#      endif
#    endif
#  else
#    define DUF_SQL_SELECTED_TMP_FILENAMES_FULL           DUF_SQL_SELECTED_TMP_FILENAMES
#    define DUF_SQL_SELECTED_TMP_PATHS_FULL               DUF_SQL_SELECTED_TMP_PATHS
#    define DUF_SQL_SELECTED_TMP_PATHTOT_FILES_FULL       DUF_SQL_SELECTED_TMP_PATHTOT_FILES
#    define DUF_SQL_SELECTED_TMP_PATHTOT_DIRS_FULL        DUF_SQL_SELECTED_TMP_PATHTOT_DIRS
#  endif

#endif
