find duf_optimpl_enum.def
sfind duf_optimpl_enum_trace.def
sfind duf_optimpl_enum_filter_minmax.def
sfind duf_optimpl_enum_filter_same_minmax.def 

tab sfind duf_config_act_enum.def
sfind duf_config_puz_enum.def
sfind duf_config_disable_enum.def
