#ifndef MAS_QSTD_STRUCTS_H
# define MAS_QSTD_STRUCTS_H

# include <mastar/mysqlpfs/mysqlpfs_types.h>

/* TODO rename mas_qstd_id_e */
enum mas_qstd_id_e
{
  STD_MSTMT_INSERT_NAMES,
  STD_MSTMT_SELECT_NAMES_ID,
  STD_MSTMT_INSERT_PARENTS,
  STD_MSTMT_SELECT_PARENTS_ID,
  STD_MSTMT_INSERT_SIZES,
  STD_MSTMT_SELECT_SIZES_ID,
  STD_MSTMT_INSERT_DATAS,
  STD_MSTMT_SELECT_DATAS_ID,
  STD_MSTMT_INSERT_PROPS,
  STD_MSTMT_SELECT_PROPS_ID,
  STD_MSTMT_SELECT_NODES_ID,
  STD_MSTMT_MAX
};
enum mas_qstd_nfields_e
{
  STD_MSTMT_INSERT_NRESULTS = 0,

  STD_MSTMT_SELECT_NAMES_NFIELDS = 2,
  STD_MSTMT_INSERT_NAMES_NFIELDS = 4,
  STD_MSTMT_SELECT_NAMES_NRESULTS = 1,

  STD_MSTMT_SELECT_NODES_NFIELDS = 2,
  STD_MSTMT_SELECT_NODES_NRESULTS=1,

  STD_MSTMT_INSERT_PROPS_NFIELDS = 12,
  STD_MSTMT_SELECT_PROPS_NFIELDS = 1,
  STD_MSTMT_SELECT_PROPS_NRESULTS = 1,

  STD_MSTMT_SELECT_SIZES_NFIELDS = 1,
  STD_MSTMT_INSERT_SIZES_NFIELDS = 1,
  STD_MSTMT_SELECT_SIZES_NRESULTS = 1,

  STD_MSTMT_SELECT_DATAS_NFIELDS = 2,
  STD_MSTMT_INSERT_DATAS_NFIELDS = 3,
  STD_MSTMT_SELECT_DATAS_NRESULTS = 1,

  STD_MSTMT_SELECT_PARENTS_NFIELDS = 1,
  STD_MSTMT_INSERT_PARENTS_NFIELDS = 1,
  STD_MSTMT_SELECT_PARENTS_NRESULTS = 1,

};
struct mas_qstd_s
{
  mysqlpfs_t *pfs;
  mysqlpfs_mstmt_t **std_mstmts;
};

#endif
