#ifndef MAS_SQLITE_CONST_H
#  define MAS_SQLITE_CONST_H

#  include <sqlite3.h>

typedef enum
{
  MAS_SQLITE_ERROR_BASE = -59999,
  DUF_SQL_ERROR = MAS_SQLITE_ERROR_BASE + SQLITE_ERROR, /*          #define SQLITE_ERROR       1  SQL error or missing database              */
  DUF_SQL_INTERNAL = MAS_SQLITE_ERROR_BASE + SQLITE_INTERNAL, /*    #define SQLITE_INTERNAL    2  Internal logic error in SQLite             */
  DUF_SQL_PERM = MAS_SQLITE_ERROR_BASE + SQLITE_PERM, /*            #define SQLITE_PERM        3  Access permission denied                   */
  DUF_SQL_ABORT = MAS_SQLITE_ERROR_BASE + SQLITE_ABORT, /*          #define SQLITE_ABORT       4  Callback routine requested an abort        */
  DUF_SQL_BUSY = MAS_SQLITE_ERROR_BASE + SQLITE_BUSY, /*            #define SQLITE_BUSY        5  The database file is locked                */
  DUF_SQL_LOCKED = MAS_SQLITE_ERROR_BASE + SQLITE_LOCKED, /*        #define SQLITE_LOCKED      6  A table in the database is locked          */
  DUF_SQL_NOMEM = MAS_SQLITE_ERROR_BASE + SQLITE_NOMEM, /*          #define SQLITE_NOMEM       7  A malloc() failed                          */
  DUF_SQL_READONLY = MAS_SQLITE_ERROR_BASE + SQLITE_READONLY, /*    #define SQLITE_READONLY    8  Attempt to write a readonly database       */
  DUF_SQL_INTERRUPT = MAS_SQLITE_ERROR_BASE + SQLITE_INTERRUPT, /*  #define SQLITE_INTERRUPT   9  Operation terminated by sqlite3_interrupt() */
  DUF_SQL_IOERR = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR, /*          #define SQLITE_IOERR      10  Some kind of disk I/O error occurred       */
  DUF_SQL_CORRUPT = MAS_SQLITE_ERROR_BASE + SQLITE_CORRUPT, /*      #define SQLITE_CORRUPT    11  The database disk image is malformed       */
  DUF_SQL_NOTFOUND = MAS_SQLITE_ERROR_BASE + SQLITE_NOTFOUND, /*    #define SQLITE_NOTFOUND   12  Unknown opcode in sqlite3_file_control()   */
  DUF_SQL_FULL = MAS_SQLITE_ERROR_BASE + SQLITE_FULL, /*            #define SQLITE_FULL       13  Insertion failed because database is full  */
  DUF_SQL_CANTOPEN = MAS_SQLITE_ERROR_BASE + SQLITE_CANTOPEN, /*    #define SQLITE_CANTOPEN   14  Unable to open the database file           */
  DUF_SQL_PROTOCOL = MAS_SQLITE_ERROR_BASE + SQLITE_PROTOCOL, /*    #define SQLITE_PROTOCOL   15  Database lock protocol error               */
  DUF_SQL_EMPTY = MAS_SQLITE_ERROR_BASE + SQLITE_EMPTY, /*          #define SQLITE_EMPTY      16  Database is empty                          */
  DUF_SQL_SCHEMA = MAS_SQLITE_ERROR_BASE + SQLITE_SCHEMA, /*        #define SQLITE_SCHEMA     17  The database schema changed                */
  DUF_SQL_TOOBIG = MAS_SQLITE_ERROR_BASE + SQLITE_TOOBIG, /*        #define SQLITE_TOOBIG     18  String or BLOB exceeds size limit          */
  DUF_SQL_CONSTRAINT = MAS_SQLITE_ERROR_BASE + SQLITE_CONSTRAINT, /*#define SQLITE_CONSTRAINT 19  Abort due to constraint violation          */
  DUF_SQL_MISMATCH = MAS_SQLITE_ERROR_BASE + SQLITE_MISMATCH, /*    #define SQLITE_MISMATCH   20  Data type mismatch                         */
  DUF_SQL_MISUSE = MAS_SQLITE_ERROR_BASE + SQLITE_MISUSE, /*        #define SQLITE_MISUSE     21  Library used incorrectly                   */
  DUF_SQL_NOLFS = MAS_SQLITE_ERROR_BASE + SQLITE_NOLFS, /*          #define SQLITE_NOLFS      22  Uses OS features not supported on host     */
  DUF_SQL_AUTH = MAS_SQLITE_ERROR_BASE + SQLITE_AUTH, /*            #define SQLITE_AUTH       23  Authorization denied                       */
  DUF_SQL_FORMAT = MAS_SQLITE_ERROR_BASE + SQLITE_FORMAT, /*        #define SQLITE_FORMAT     24  Auxiliary database format error            */
  DUF_SQL_RANGE = MAS_SQLITE_ERROR_BASE + SQLITE_RANGE, /*          #define SQLITE_RANGE      25  2nd parameter to sqlite3_bind out of range */
  DUF_SQL_NOTADB = MAS_SQLITE_ERROR_BASE + SQLITE_NOTADB, /*        #define SQLITE_NOTADB     26  File opened that is not a database file    */
  DUF_SQL_NOTICE = MAS_SQLITE_ERROR_BASE + SQLITE_NOTICE, /*        #define SQLITE_NOTICE     27  Notifications from sqlite3_log()           */
  DUF_SQL_WARNING = MAS_SQLITE_ERROR_BASE + SQLITE_WARNING, /*      #define SQLITE_WARNING    28  Warnings from sqlite3_log()                */
  DUF_SQL_ROW = MAS_SQLITE_ERROR_BASE + SQLITE_ROW, /*              #define SQLITE_ROW        100 sqlite3_step() has another row ready       */
  DUF_SQL_DONE = MAS_SQLITE_ERROR_BASE + SQLITE_DONE, /*            #define SQLITE_DONE       101 sqlite3_step() has finished executing      */
/* extended */
  DUF_SQL_IOERR_READ = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_READ,
  DUF_SQL_IOERR_SHORT_READ = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_SHORT_READ,
  DUF_SQL_IOERR_WRITE = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_WRITE,
  DUF_SQL_IOERR_FSYNC = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_FSYNC,
  DUF_SQL_IOERR_DIR_FSYNC = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_DIR_FSYNC,
  DUF_SQL_IOERR_TRUNCATE = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_TRUNCATE,
  DUF_SQL_IOERR_FSTAT = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_FSTAT,
  DUF_SQL_IOERR_UNLOCK = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_UNLOCK,
  DUF_SQL_IOERR_RDLOCK = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_RDLOCK,
  DUF_SQL_IOERR_DELETE = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_DELETE,
  DUF_SQL_IOERR_BLOCKED = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_BLOCKED,
  DUF_SQL_IOERR_NOMEM = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_NOMEM,
  DUF_SQL_IOERR_ACCESS = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_ACCESS,
  DUF_SQL_IOERR_CHECKRESERVEDLOCK = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_CHECKRESERVEDLOCK,
  DUF_SQL_IOERR_LOCK = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_LOCK,
  DUF_SQL_IOERR_CLOSE = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_CLOSE,
  DUF_SQL_IOERR_DIR_CLOSE = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_DIR_CLOSE,
  DUF_SQL_IOERR_SHMOPEN = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_SHMOPEN,
  DUF_SQL_IOERR_SHMSIZE = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_SHMSIZE,
  DUF_SQL_IOERR_SHMLOCK = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_SHMLOCK,
  DUF_SQL_IOERR_SHMMAP = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_SHMMAP,
  DUF_SQL_IOERR_SEEK = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_SEEK,
  DUF_SQL_IOERR_DELETE_NOENT = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_DELETE_NOENT,
  DUF_SQL_IOERR_MMAP = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_MMAP,
  DUF_SQL_IOERR_GETTEMPPATH = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_GETTEMPPATH,
  DUF_SQL_IOERR_CONVPATH = MAS_SQLITE_ERROR_BASE + SQLITE_IOERR_CONVPATH,
  DUF_SQL_LOCKED_SHAREDCACHE = MAS_SQLITE_ERROR_BASE + SQLITE_LOCKED_SHAREDCACHE,
  DUF_SQL_BUSY_RECOVERY = MAS_SQLITE_ERROR_BASE + SQLITE_BUSY_RECOVERY,
  DUF_SQL_BUSY_SNAPSHOT = MAS_SQLITE_ERROR_BASE + SQLITE_BUSY_SNAPSHOT,
  DUF_SQL_CANTOPEN_NOTEMPDIR = MAS_SQLITE_ERROR_BASE + SQLITE_CANTOPEN_NOTEMPDIR,
  DUF_SQL_CANTOPEN_ISDIR = MAS_SQLITE_ERROR_BASE + SQLITE_CANTOPEN_ISDIR,
  DUF_SQL_CANTOPEN_FULLPATH = MAS_SQLITE_ERROR_BASE + SQLITE_CANTOPEN_FULLPATH,
  DUF_SQL_CANTOPEN_CONVPATH = MAS_SQLITE_ERROR_BASE + SQLITE_CANTOPEN_CONVPATH,
  DUF_SQL_CORRUPT_VTAB = MAS_SQLITE_ERROR_BASE + SQLITE_CORRUPT_VTAB,
  DUF_SQL_READONLY_RECOVERY = MAS_SQLITE_ERROR_BASE + SQLITE_READONLY_RECOVERY,
  DUF_SQL_READONLY_CANTLOCK = MAS_SQLITE_ERROR_BASE + SQLITE_READONLY_CANTLOCK,
  DUF_SQL_READONLY_ROLLBACK = MAS_SQLITE_ERROR_BASE + SQLITE_READONLY_ROLLBACK,
  DUF_SQL_READONLY_DBMOVED = MAS_SQLITE_ERROR_BASE + SQLITE_READONLY_DBMOVED,
  DUF_SQL_ABORT_ROLLBACK = MAS_SQLITE_ERROR_BASE + SQLITE_ABORT_ROLLBACK,
  DUF_SQL_CONSTRAINT_CHECK = MAS_SQLITE_ERROR_BASE + SQLITE_CONSTRAINT_CHECK,
  DUF_SQL_CONSTRAINT_COMMITHOOK = MAS_SQLITE_ERROR_BASE + SQLITE_CONSTRAINT_COMMITHOOK,
  DUF_SQL_CONSTRAINT_FOREIGNKEY = MAS_SQLITE_ERROR_BASE + SQLITE_CONSTRAINT_FOREIGNKEY,
  DUF_SQL_CONSTRAINT_FUNCTION = MAS_SQLITE_ERROR_BASE + SQLITE_CONSTRAINT_FUNCTION,
  DUF_SQL_CONSTRAINT_NOTNULL = MAS_SQLITE_ERROR_BASE + SQLITE_CONSTRAINT_NOTNULL,
  DUF_SQL_CONSTRAINT_PRIMARYKEY = MAS_SQLITE_ERROR_BASE + SQLITE_CONSTRAINT_PRIMARYKEY,
  DUF_SQL_CONSTRAINT_TRIGGER = MAS_SQLITE_ERROR_BASE + SQLITE_CONSTRAINT_TRIGGER,
  DUF_SQL_CONSTRAINT_UNIQUE = MAS_SQLITE_ERROR_BASE + SQLITE_CONSTRAINT_UNIQUE,
  DUF_SQL_CONSTRAINT_VTAB = MAS_SQLITE_ERROR_BASE + SQLITE_CONSTRAINT_VTAB,
  DUF_SQL_CONSTRAINT_ROWID = MAS_SQLITE_ERROR_BASE + SQLITE_CONSTRAINT_ROWID,
  DUF_SQL_NOTICE_RECOVER_WAL = MAS_SQLITE_ERROR_BASE + SQLITE_NOTICE_RECOVER_WAL,
  DUF_SQL_NOTICE_RECOVER_ROLLBACK = MAS_SQLITE_ERROR_BASE + SQLITE_NOTICE_RECOVER_ROLLBACK,
  DUF_SQL_WARNING_AUTOINDEX = MAS_SQLITE_ERROR_BASE + SQLITE_WARNING_AUTOINDEX,
} duf_sqlite_code_t;


/* #  define SQLITE_OK           0 (* Successful result *)                           */
































#endif
