#ifndef MAS_LIST_H
#  define MAS_LIST_H

#  include <sys/queue.h>


#  if 1
#    define MAS_LIST_HEAD STAILQ_HEAD
#    define MAS_LIST_ENTRY STAILQ_ENTRY
#    define MAS_LIST_INIT STAILQ_INIT
/* #    define MAS_LIST_ADD STAILQ_INSERT_HEAD */
#    define MAS_LIST_ADD STAILQ_INSERT_TAIL
#    define MAS_LIST_FOREACH STAILQ_FOREACH
#    define MAS_LIST_FOREACH_SAFE STAILQ_FOREACH_SAFE
#    define MAS_LIST_FIRST STAILQ_FIRST
#    define MAS_LIST_REMOVE STAILQ_REMOVE
#    define MAS_LIST_EMPTY STAILQ_EMPTY
#    define MAS_LIST_REMOVE_HEAD STAILQ_REMOVE_HEAD
#    define MAS_LIST_NEXT STAILQ_NEXT
#  else
#    define MAS_LIST_HEAD SLIST_HEAD
#    define MAS_LIST_ENTRY SLIST_ENTRY
#    define MAS_LIST_INIT SLIST_INIT
#    define MAS_LIST_ADD SLIST_INSERT_HEAD
#    define MAS_LIST_FOREACH SLIST_FOREACH
#    define MAS_LIST_FOREACH_SAFE SLIST_FOREACH_SAFE
#    define MAS_LIST_FIRST SLIST_FIRST
#    define MAS_LIST_REMOVE SLIST_REMOVE
#    define MAS_LIST_EMPTY SLIST_EMPTY
#    define MAS_LIST_REMOVE_HEAD SLIST_REMOVE_HEAD
#    define MAS_LIST_NEXT SLIST_NEXT
#  endif


#  undef MAS_WEAK
#endif
